--liquibase formatted sql

--changeset derkachev:1
CREATE TABLE tasks
(
    id             BIGINT generated by default as identity primary key,
    message        TEXT      NOT NULL,
    chat_id        BIGINT    NOT NULL,
    task_date_time TIMESTAMP NOT NULL
);